package com.example.abl.model

data class LeadsItem(
    val address: String,
    val age: String,
    val campaign_id: String,
    val city: String,
    val date_of_transfer: String,
    val department: String,
    val desc: String,
    val email_address: String,
    val employment: String,
    val expected_amount: String,
    val expected_closure_date: String,
    val first_name: String,
    val gender: String,
    val get_previous_visit: List<GetPreviousVisit>,
    val home_phone_number: String,
    val job_title: String,
    val last_name: String,
    val lead_id: String,
    val lead_status: String,
    val lead_status_name: String,
    val marital_status: String,
    val mobile_phone_number: String,
    val name: String,
    val office_phone_number: String,
    val potential_amount: String,
    val probability: String,
    val product_id: String,
    val product_name: String,
    val region: String,
    val source: String
)